trigger:
- main

pool:
  pool-terra

steps:
- script: echo k8s!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: DownloadSecureFile@1
  name: 
  inputs:
    secureFile: 'azure_rsa.pub'
- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)//configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'service-terra-connection'
    backendAzureRmTenantId: '352962f9-1e3b-435e-a99b-2afe78acad69'
    backendAzureRmSubscriptionId: '3cd1cc07-05ab-4763-b8f9-d92482d09c44'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'mygsource'
    backendAzureRmResourceGroupLocation: 'northeurope'
    backendAzureRmStorageAccountName: 'prags@93'
    backendAzureRmContainerName: 'prags@93container'
    backendAzureRmKey: 'terra-devops.tfstate'
    allowTelemetryCollection: true